# -*- coding: utf-8 -*-
"""Jeanmarcos Kai Project Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F1TJn_mYAIe5vI3IPLmlV52DrTVRDSDr
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import HistGradientBoostingRegressor

train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")

print(test.shape)
print(train.shape)

display = ["neighbourhood_group","latitude", "longitude", "number_of_reviews", "reviews_per_month", "calculated_host_listings_count", "minimum_nights", "availability_365", "price"]
train[display].head()

"""**Acknowledgements: code adapted from Parker Seegmiller's 9/29/23 xhour**"""

### first attempt, do not run ###
#
# features = ["latitude", "longitude", "number_of_reviews", "reviews_per_month", "calculated_host_listings_count", "minimum_nights", "availability_365"]
# x = train[features]
# y = train["price"]

# x_test = test[features]

# clf = RandomForestClassifier(max_depth= 10, random_state= 27, criterion= "log_loss")
# clf.fit(x,y)

# pred_y = clf.predict(x_test)

# submission_data = {"id": test["id"], "price": pred_y}
# submission_df = pd.DataFrame(submission_data)

# how to create submission file
# submission_df.to_csv("submission12.csv", index=False)

# things to try -----
# create own columns
# different kind of model
# same model with different hyperparameters
# balanced class model
# encode string as number

### second attempt, do not run ###
#
# features = ["latitude", "longitude", "number_of_reviews", "reviews_per_month", "calculated_host_listings_count", "minimum_nights", "availability_365"]
# x = train[features]
# y = train["price"]

# x_test = test[features]

# clf = RandomForestRegressor(max_depth = 10, random_state= 27, criterion= "poisson")
# clf.fit(x,y)

# pred_y = clf.predict(x_test)

# submission_data = {"id": test["id"], "price": pred_y}
# submission_df = pd.DataFrame(submission_data)

# # how to create submission file
# submission_df.to_csv("submission16.csv", index=False)

### final and best attempt
features = ["latitude", "longitude", "number_of_reviews", "reviews_per_month", "calculated_host_listings_count", "minimum_nights", "availability_365"]
x = train[features]
y = train["price"]

x_test = test[features]

clf = HistGradientBoostingRegressor(loss="poisson", max_depth= 10)
clf.fit(x,y)

pred_y = clf.predict(x_test)

submission_data = {"id": test["id"], "price": pred_y}
submission_df = pd.DataFrame(submission_data)

# change file name to final_submission when done
submission_df.to_csv("final_submission.csv", index=False)